# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 79, 781, 511))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(360, 20, 71, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(340, 90, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 140, 113, 21))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.loginbtn = QtWidgets.QPushButton(self.page)
        self.loginbtn.setGeometry(QtCore.QRect(340, 190, 113, 32))
        self.loginbtn.setObjectName("loginbtn")
        self.toregisterbtn = QtWidgets.QCommandLinkButton(self.page)
        self.toregisterbtn.setGeometry(QtCore.QRect(470, 190, 193, 41))
        self.toregisterbtn.setObjectName("toregisterbtn")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 91, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 70, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(350, 120, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(380, 170, 60, 16))
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(self.page_2)
        self.radioButton.setGeometry(QtCore.QRect(300, 200, 100, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.page_2)
        self.radioButton_2.setGeometry(QtCore.QRect(450, 200, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(370, 250, 81, 16))
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(self.page_2)
        self.checkBox.setGeometry(QtCore.QRect(280, 280, 87, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_2.setGeometry(QtCore.QRect(400, 280, 87, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_3.setGeometry(QtCore.QRect(520, 280, 87, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.savebtn = QtWidgets.QPushButton(self.page_2)
        self.savebtn.setGeometry(QtCore.QRect(360, 340, 113, 32))
        self.savebtn.setObjectName("savebtn")
        self.backbtn = QtWidgets.QCommandLinkButton(self.page_2)
        self.backbtn.setGeometry(QtCore.QRect(530, 340, 193, 41))
        self.backbtn.setObjectName("backbtn")
        self.stackedWidget.addWidget(self.page_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 20, 141, 20))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.toregisterbtn.clicked.connect(MainWindow.onregister)
        self.backbtn.clicked.connect(MainWindow.onlogin)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login Here"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.loginbtn.setText(_translate("MainWindow", "Login"))
        self.toregisterbtn.setText(_translate("MainWindow", "Register"))
        self.label_2.setText(_translate("MainWindow", "Register Here"))
        self.label_4.setText(_translate("MainWindow", "Gender"))
        self.radioButton.setText(_translate("MainWindow", "Male"))
        self.radioButton_2.setText(_translate("MainWindow", "Female"))
        self.label_5.setText(_translate("MainWindow", "Preferences"))
        self.checkBox.setText(_translate("MainWindow", "Travel"))
        self.checkBox_2.setText(_translate("MainWindow", "Shopping"))
        self.checkBox_3.setText(_translate("MainWindow", "Sports"))
        self.savebtn.setText(_translate("MainWindow", "Save"))
        self.backbtn.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "My Library Application"))

